### ISSUE TITLE
Takes 10 minutes to get 10 results (unnecessary complicated start of the run?)

### ISSUE THREAD

**Issue by zpelechova** [dtrungtin/actor-airbnb-scraper#11]
Because it runs prepares itself for much bigger run - doesn't make sense - if there is maximum items low to put it in smaller chunks (like proce from 100-200) - https://my.apify.com/view/runs/5h9HmHxxGmYQ52Lf6

**Comment by pocesar** [comment]
this is due to the outside requests, this needs a makeover

**Comment by dtrungtin** [comment]
Please retry. It should be faster.
https://my.apify.com/tasks/bqwJe7wcuwVwedRLQ#/runs/5YNX6MVgXr0Bg7gmV

**Comment by zpelechova** [comment]
Wow, it is fast compared to before!!!

**Comment by zpelechova** [comment]
fixed 07/21.
