### ISSUE TITLE
Get rooms far from location

### ISSUE THREAD

**Issue by zpelechova** [dtrungtin/actor-airbnb-scraper#13]
https://my.apify.com/view/runs/5h9HmHxxGmYQ52Lf6

**Comment by dtrungtin** [comment]
Please give more details.

**Comment by zpelechova** [comment]
When I have Sydney on input I suppose I wil get places from Sydney and not https://www.airbnb.cz/rooms/19352965/location?_set_bev_on_new_domain=1617217162_NDhkYjI5OTFkZmZl&source_impression_id=p3_1623679506_q6Ars2iChufpSfjh&guests=1&adults=1

**Comment by dtrungtin** [comment]
I see. The result are from airbnb so we cannot do anything here.
Maybe use other keywords for location to search more exactly.
