### ISSUE TITLE
input from gslink doesnt work

### ISSUE THREAD

**Issue by zpelechova** [dtrungtin/actor-airbnb-scraper#21]

**Comment by dtrungtin** [comment]
I don't understand what gslink url means. If it's short url, we don't support as it's not browser crawling.

**Comment by metalwarrior665** [comment]
Google Sheets link in Start URLs.

@zpelechova Let's not use shortcuts like this pls

**Comment by dtrungtin** [comment]
Fixed. https://github.com/dtrungtin/actor-airbnb-scraper/commit/25155a5b0a4936376c047edffc02f8b3ba2db0ec

**Comment by zpelechova** [comment]
Fixed 05/21
