### ISSUE TITLE
Max reviews doesnt work

### ISSUE THREAD

**Issue by zpelechova** [dtrungtin/actor-airbnb-scraper#23]
I ahve limit 3 and get 173. https://my.apify.com/view/runs/vhQK9JyweSmeHPpJm

**Comment by dtrungtin** [comment]
Fixed.
https://github.com/dtrungtin/actor-airbnb-scraper/commit/3625b2ad6133871213683e33eb4bfb365c2da8a9

**Comment by zpelechova** [comment]
Fixed 05/21
