### ISSUE TITLE
Calendar is sometimes scraped and sometimes not.

### ISSUE THREAD

**Issue by zpelechova** [dtrungtin/actor-airbnb-scraper#24]
Here it is: https://my.apify.com/view/runs/d35FGaAhsDS9Bbdaw
Here it is not: https://my.apify.com/view/runs/vhQK9JyweSmeHPpJm

**Comment by dtrungtin** [comment]
Please see the log:
2021-04-07T09:59:43.268Z ERROR Error while retrieving calendar {"url":"https://api.airbnb.com/v2/pdp_listing_details/28147622?_format=for_native","id":28147622}

Sometime the request to get calendar has an error. It's better to use better proxy as RESIDENTIAL to prevent such error.

**Comment by zpelechova** [comment]
When it gets the error does it retry?

**Comment by dtrungtin** [comment]
network issue => try to use reliable proxy as RESIDENTIAL to prevent such error.
do some retries already.

**Comment by zpelechova** [comment]
How many times does it retry?

**Comment by dtrungtin** [comment]
10 times the same as calling other APIs.
