### ISSUE TITLE
There are a lot of errors in the log

### ISSUE THREAD

**Issue by zpelechova** [dtrungtin/actor-airbnb-scraper#25]
It might put off users even when the scrape is succesfull in the end.
https://my.apify.com/view/runs/SO2pxPNn0CqBQzbsb

**Comment by dtrungtin** [comment]
I don't think it's bug.
These errors are the requests to Airbnb server returning the error. It may bot protection, network issues, etc. However, we have some retries on such request.
Solution:
+ Hide the errors (I don't like this option)
+ Choose other better proxies as Residential to run the actor

**Comment by zpelechova** [comment]
YOu may hide some errors or make it part of debug log - maybe a best option? As this way the user thinks it is not wirking especially with airbnb where first results takes 30 minutes to get.

**Comment by dtrungtin** [comment]
ERROR BasicCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue

It's error log, not a debug log.
Like other actors, If there is an error when crawling 1 request URL, it should be logged as ERROR and then retry to crawling this request URL again.
