### ISSUE TITLE
How to find API key?

### ISSUE THREAD

**Issue by Patrick-Erichsen** [dtrungtin/actor-airbnb-scraper#27]
Hello,

I came across this actor on Apify and would like to try and run it on my local machine.

How can I get access to my API key for Airbnb? I have read some other Readmes that mentioned looking at requests to the `/explore_tabs` endpoint for the key, but with the v3 update, this request is no longer being made.

I would like to run this locally because I want to scrape Airbnb listings that have the WiFi speed listed in the amenity sections, e.g. `WiFi - 100mbps`.

Thanks for the guidance!

**Comment by pocesar** [comment]
their API key is on their v2 endpoints on their website
