### ISSUE TITLE
process.exit(0) should not be used

### ISSUE THREAD

**Issue by pocesar** [dtrungtin/actor-airbnb-scraper#29]
process.exit(0) will skip the statistics and writing settling RequestQueue handled request that can lead to unexpected behavior if the scraper is resurrected. https://github.com/dtrungtin/actor-airbnb-scraper/commit/5553c358bb1eb3e96db195db3d985adefbd26ebc#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R296 

please keep the `await autoscaledPool.abort()`, as it's now under [crawler.autoscaledPool](https://sdk.apify.com/docs/guides/migration-to-v1#autoscaledpool-was-moved-under-crawlingcontextcrawler)

**Comment by zpelechova** [comment]
@pocesar Could you please briefly check if I can close this one?

**Comment by pocesar** [comment]
@zpelechova yes, it's fixed

**Comment by zpelechova** [comment]
fixed 07/21
