### ISSUE TITLE
Add new fields in the dataset

### ISSUE THREAD

**Issue by zpelechova** [dtrungtin/actor-airbnb-scraper#32]
Host URL
Number of listings host has

Required by a prospected customer.

**Comment by zpelechova** [comment]
It only works with detailed scrape but it is not states so anywhere nor logically added to the input.

**Comment by dtrungtin** [comment]
You need to set "addMoreHostInfo": true, to the INPUT.
You will see these attributes:
"hostUrl": "https://www.airbnb.com.vn/users/show/72260524",
    "listingsCount": 1,
    "totalListingsCount": 1

Not sure what you mean here? What do I need to update?

**Comment by dtrungtin** [comment]
Just added the tooltip "Only work if the Extract main listing information only (no detail) is unchecked.
