### ISSUE TITLE
How to retrieve the prices

### ISSUE THREAD

**Issue by rafagsiqueira** [dtrungtin/actor-airbnb-scraper#5]
Thank you for this scraper and sorry if this is a silly question, but I can't seem to retrieve the prices of the listings. Am I doing something wrong?

**Comment by markoneill6** [comment]
Hi, I have the same question @rafagsiqueira. I can't get the prices back?

**Comment by pocesar** [comment]
prices require a second call to their new API endpoint (/v3) and doesn't have a quick way to get those prices, I'll dig around for the /v2 endpoint

**Comment by pocesar** [comment]
@markoneill6 @rafagsiqueira  this is available in the latest version on the platform, under `pricing` object in the dataset
